// Auto-generated by skills/codebase-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/architecture/": [
    {
      "text": "架构分析",
      "items": [
        {
          "text": "A-001 Agent Adapter 体系架构详解",
          "link": "/architecture/20260505-agent-adapter-architecture"
        },
        {
          "text": "A-002 Preview 渲染体系架构详解",
          "link": "/architecture/20260505-preview-rendering-architecture"
        },
        {
          "text": "A-003 Local CLI Agent 连接架构详解",
          "link": "/architecture/20260506-opencode-local-cli-architecture"
        }
      ]
    }
  ],
  "/discussion/": [
    {
      "text": "技术讨论",
      "items": []
    }
  ],
  "/issue/": [
    {
      "text": "Issue 记录",
      "items": []
    }
  ],
  "/reference/": [
    {
      "text": "参考手册",
      "items": [
        {
          "text": "R-001 Agent 适配器速查表",
          "link": "/reference/20260505-agent-adapter-quick-reference"
        }
      ]
    }
  ],
  "/roadmap/": [
    {
      "text": "规划路线",
      "items": []
    }
  ]
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX"
  },
  {
    "text": "架构分析",
    "link": "/architecture/20260505-agent-adapter-architecture"
  },
  {
    "text": "参考手册",
    "link": "/reference/20260505-agent-adapter-quick-reference"
  }
];
